Repository Amool-kk/To-Learn-Problems, pull requests merged in 2022-10, with the labels that each got.

#2 setup react js frontend
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/index.js
Labels: help wanted, hacktoberfest

#3 [ADD] start backend using node js
  backend/app.js
  backend/package-lock.json
  backend/package.json
Labels: hacktoberfest-accepted, hacktoberfest2022

#4 [REFACTOR] Implemented Basic Backend Directory Structure
  backend/.env.example
  backend/.gitignore
  backend/app.js
  backend/config/index.js
  backend/middlewares/index.js
  backend/models/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/utils/index.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#5 [ADD] MongoDB Connection
  backend/.env.example
  backend/app.js
  backend/config/index.js
  backend/package-lock.json
  backend/package.json
  backend/utils/index.js
  backend/utils/mongo.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#6 Added HomePage and Navbar to the FrontEnd
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.js
  client/src/index.js
  client/src/pages/Articles/Articles.js
  client/src/pages/Home/Home.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 [Add] api for get tags and save tags
  backend/app.js
  backend/models/questions.js
  backend/models/tags.js
  backend/routes/index.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#7 [ADD] Admin Model and Creation Script
  backend/config/index.js
  backend/models/admin.js
  backend/models/index.js
  backend/package-lock.json
  backend/package.json
  backend/utils/admin.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#9 Added articles and cards to the project
  client/public/favicon.ico
  client/public/index.html
  client/src/App.css
  client/src/pages/Articles/Articles.css
  client/src/pages/Articles/Articles.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#10 [Add] routes for add questions and fetch questions
  backend/app.js
  backend/models/index.js
  backend/routes/index.js
  backend/routes/questions.js
  backend/routes/tag.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 Added tags to the homepage
  client/src/pages/Articles/Articles.js
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#12 [ADD] Node Mailer & Mail send to admins on creation
  backend/.env.example
  backend/config/index.js
  backend/models/admin.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/utils/admin.js
  backend/utils/index.js
  backend/utils/mailer.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 slight styling changes and refactors
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/Contexts/Buttons.css
  client/src/Contexts/Buttons.js
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.js
  client/src/pages/Articles/Articles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#14 [ADD FOOTER]
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.js
  client/src/pages/Articles/Articles.css
  client/src/pages/Home/Home.css
  client/src/pages/SignIn/SignIn.css
  client/src/pages/SignIn/SignIn.js
  client/src/pages/SignUp/SignUp.css
  client/src/pages/SignUp/SignUp.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#15 UI CHANGED
  client/src/components/Navbar/Navbar.css
  client/src/pages/SignIn/SignIn.css
  client/src/pages/SignUp/SignUp.css
  client/src/pages/SignUp/SignUp.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 [ADD] About page
  client/src/App.js
  client/src/components/Navbar/Navbar.js
  client/src/pages/About/About.css
  client/src/pages/About/About.js
  client/src/pages/About/imgg.png
  client/src/pages/SignUp/SignUp.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
